version: '3'
services:
  pgsql:
    image: postgres:12
    container_name: personal_control_db
    volumes:
      - './db:/var/lib/postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: personal_control
      POSTGRES_DB: personal_control
    ports:
      - "5434:5432"
  php:
    container_name: personal_control_web
    build:
      context: ./php
    ports:
      - '8080:80'
    volumes:
      - './src:/var/www/html'
    depends_on:
      - pgsql
